CREATE TABLE OSOBOWOSC (
	id BIGINT NOT NULL PRIMARY KEY,
	nick VARCHAR(30) NOT NULL,
	tweetyI SMALLINT,
	tweetyII SMALLINT,
	tweetyIII SMALLINT,
	dataWpisu SMALLDATETIME,
	skutecznosc SMALLINT
);

CREATE TABLE TEMATYKA (
	tag VARCHAR(30) NOT NULL PRIMARY KEY,
	skutecznosc SMALLINT
);

CREATE TABLE ZBIOROSOBOWOSCI (
	tag VARCHAR(30) NOT NULL,
	idOsobowosci BIGINT NOT NULL
);